### ISSUE TITLE
Is it possible to filter inside of a function?

### ISSUE THREAD

**Issue by dcrelling** [mankindsoftware/angular-isotope#11]
Hi great plugin. In all the examples filtering of isotope items happens with a button click. Is it possible to have the filtering applied in a custom function? For example I have a third party tag plugin where a custom function can be defined that is executed when a user creates a new tag. Ideally I would like to then apply the filtering when the new tag is created. For this to happen the easiest way I can see would be to apply the filtering inside my custom function.

Thanks

**Comment by mankindsoftware** [comment]
With the newer releases of Angular-Isotope, you can $emit an event (or do a $rootScope.$broadcast). 

Angular-Isotope listens for the following events and passes the data to Isotope's corresponding option or method command.

```
$scope.$emit('iso-option', {options});
$scope.$emit('iso-method', {name:methodName, params:optionalParameters}; 
```

For example:

```
$scope.$emit('iso-option',  {filter: '.orange'});
```

To test in the console:

```
angular.element($0).scope().$emit('iso-option', {filter: '.orange'})
```

Alternatively, you can access Isotope directly through the DOM and the isotope-container element. Let's say the element's id is 'isotopeContainer':

```
$('#isotopeContainer').isotope({filter: '.purple'})
```

Hope this helps,
Mark

see:
http://isotope.metafizzy.co/options.html
http://isotope.metafizzy.co/methods.html
