### ISSUE TITLE
How do you change the layoutMode options?

### ISSUE THREAD

**Issue by johnnysbug** [mankindsoftware/angular-isotope#3]
I didn't see in the demo app how you could change the layoutMode (for example) via a directive. For instance, if I wanted to change the layoutMode to 'cellsByRow' and then set the columnWidth, how would I do that? I am assuming I could use a directive to do this, but I haven't been able to track down any examples of the proper syntax.

**Comment by mankindsoftware** [comment]
In the "isotopeContainer" directive, there is a "iso-options" attribute whose value is passed through to Isotope. (See [http://isotope.metafizzy.co/docs/layout-modes.html](http://isotope.metafizzy.co/docs/layout-modes.html). ) This has not been thoroughly tested.

example:

``` html
<div id="isotopeContainer" isotope-container iso-options="{layoutMode:'cellsByRow', cellsByRow: {
    columnWidth: 240,
    rowHeight: 360
  }}" ></div>
```

**Comment by johnnysbug** [comment]
That is exactly what I tried, but it doesn't appear to work. As a matter of fact, adding the iso-options attribute caused the container to not add any isotope CSS changes to its isotope items.

**Comment by johnnysbug** [comment]
Upon further testing, I realized I was missing a closing curly brace. Setting iso-options as you have shown works nicely.

**Comment by donalmurtagh** [comment]
Could you update the demo to include an example of this - I tried it out, but it didn't work?
