### ISSUE TITLE
Inconsistent gutter widths

### ISSUE THREAD

**Issue by nathanwoulfe** [mankindsoftware/angular-isotope#37]
I've set up filtering as per the demo page, but am seeing variable column gutters on page load or after filtering. The column gutter reduces to half as the margins between elements are overlaid on the adjacent element.

Has this been reported previously?

EDIT - I think imagesloaded would correct this. Maybe.

**Comment by cherchyk** [comment]
it will.  it's what I'm trying to do now.  Ufortunately no demo for this case
