### ISSUE TITLE
TypeError: isotopeContainer.isotope is not a function

### ISSUE THREAD

**Issue by uiktiomasfeliz** [mankindsoftware/angular-isotope#48]
When i try to use isotope like in the demo, that error come to console.

**Comment by Coilz** [comment]
same here

**Comment by shprota** [comment]
Include jquery.js before angular or if using require.js add jquery to angular's deps.

**Comment by jewkesy** [comment]
+1 @shprota easily missed.  Thanks

**Comment by uiktiomasfeliz** [comment]
+1 @shprota
