### ISSUE TITLE
cannot call methods on isotope prior to initialization

### ISSUE THREAD

**Issue by markdturner** [mankindsoftware/angular-isotope#57]
Every time I'm on a view that uses an isotope layout, and then navigate away from that view, an error for every isotope item is thrown.

For example if I have 25 items in a list laid out with isotope, I navigate to a new view and get 25 errors in the console:

> 'jquery.isotope.js:1360 cannot call methods on isotope prior to initialization; attempted to call method 'remove''

Obviously this error is coming from with the isotope jQuery library, but is this a symptom of something I'm doing wrong with the directive?

**Comment by hartjo** [comment]
i have the same error can you please tell me if you solve the problem thanks

**Comment by markdturner** [comment]
Sorry @hartjo, I've still not been able to solve it. It doesn't seem to break my application, its just annoying when trying to debug other things.

**Comment by hartjo** [comment]
yes it is just hate when errors like that appear on my console... even thou its not affecting my application.. anyway thanks :+1:

**Comment by hartjo** [comment]
if you want to remove the error

at isotope.pkgd.js i comment the code at line 60

var logError = typeof console === 'undefined' ? noop :
  function( message ) {
    //console.error( message );
  };

that hide the error message
