### ISSUE TITLE
How to reloadItems

### ISSUE THREAD

**Issue by Hounddog** [mankindsoftware/angular-isotope#7]
I dont know how i could programmatically reloadItems using your module. 

It would be great if you can provide some example maybee.

**Comment by dv336699** [comment]
Asked the same thing https://github.com/mankindsoftware/angular-isotope/issues/5

**Comment by Hounddog** [comment]
My actual issue here is that when i remove items i just have a gap in the grid.

**Comment by dv336699** [comment]
Try to use the refreshEvent config and set something like refreshIsotope then broadcast.
`// Config
    angular.module('iso.config', [])
    .value('iso.config', {
        debug: true,
        refreshEvent: 'refreshIsotope'
    });`

**Comment by Hounddog** [comment]
Am a bit new to angular so i am not sure how i would do this.

**Comment by Hounddog** [comment]
I have added a remove function to the demo like this

```
<script>
        var addToList = function() {
          var s=angular.element('#isotopeContainer').scope();
          s.count = s.count || 0;
          newItem={name:'add', number:s.count--, date: Date.now(), class:'purple'};
          s.$apply(s.xList.push(newItem));
        }
        var removeFromList = function() {
          var $container = angular.element('#isotopeContainer');
          var $firstTwoElems = $container.data('isotope')
          .$filteredAtoms.filter( function( i ) {
            return i < 2 ;
          });

          $container
            .isotope( 'remove', $firstTwoElems, function() {
              console.log('items removed')
          });
        }
      </script>
      <li><a onClick="addToList()">Add to List</a>
      <li><a onClick="removeFromList()">Remove from List</a>
```

**Comment by mankindsoftware** [comment]
You can now send an iso-options or iso-method events to the isotope container and the corresponding method will be called in Isotope.

```
$scope.$emit('iso-option', {options};
$scope.$emit('iso-method', {name:methodName, params:optionalParameters};
```

e.g.

```
$scope.$emit('iso-option', {sortBy:'original-order'}); 
$scope.$emit('iso-method', {name: reloadItems, params:null});
```
